export const UPDATE_SLIDER = "UPDATE_SLIDER";
export const UPDATE_FIELD = "UPDATE_FIELD";
export const BLUR_FIELD = "BLUR_FIELD";
export const SUBMIT_FORM = "SUBMIT_FORM";
export const SET_SCROLL_TO_ERRORS = "SET_SCROLL_TO_ERRORS";
